name: Linux (x64)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Publish
      working-directory: Application
      run: dotnet publish -c ${{matrix.configuration}} -r linux-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
    
    - uses: actions/upload-artifact@v3
      with:
        name: sim-artifact
        path: |
          Application/bin/${{matrix.configuration}}/net6.0/linux-x64/publish/*
          !Application/bin/${{matrix.configuration}}/net6.0/linux-x64/publish/*.pdb
