name: Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        runtime: [win-x64, linux-x64]
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Publish
      working-directory: Application
      run: dotnet publish -c ${{matrix.configuration}} -r ${{matrix.runtime}} --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesForSelfExtract=true
    
    - uses: actions/upload-artifact@v3
      with:
        name: artifact-${{matrix.runtime}}-${{matrix.configuration}}
        path: |
          Application/bin/${{matrix.configuration}}/net6.0/${{matrix.runtime}}/publish/*
          !Application/bin/${{matrix.configuration}}/net6.0/${{matrix.runtime}}/publish/*.pdb
